# coding: utf-8

"""
    General Liquidity: The Machine Economy API

    General Liquidity (GL) is one governed surface over payment, commerce, identity, and provenance for the machine economy. A caller submits a signed `Intent`, a deny-first gate decides, and only the server holds the settle primitive, so the caller never does. The wire convention is `snake_case`. 

    The version of the OpenAPI document: 2026-07-24
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from general_liquidity.api.money_api import MoneyApi


class TestMoneyApi(unittest.TestCase):
    """MoneyApi unit test stubs"""

    def setUp(self) -> None:
        self.api = MoneyApi()

    def tearDown(self) -> None:
        pass

    def test_pay(self) -> None:
        """Test case for pay

        Submit a signed Intent; the gate decides and settles.
        """
        pass


if __name__ == '__main__':
    unittest.main()
