# coding: utf-8

"""
    General Liquidity: The Machine Economy API

    General Liquidity (GL) is one governed surface over payment, commerce, identity, and provenance for the machine economy. A caller submits a signed `Intent`, a deny-first gate decides, and only the server holds the settle primitive, so the caller never does. The wire convention is `snake_case`. 

    The version of the OpenAPI document: 2026-07-25
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from general_liquidity.models.remember_request import RememberRequest

class TestRememberRequest(unittest.TestCase):
    """RememberRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RememberRequest:
        """Test RememberRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RememberRequest`
        """
        model = RememberRequest()
        if include_optional:
            return RememberRequest(
                mandate = general_liquidity.models.memory_mandate.MemoryMandate(
                    namespace = '', 
                    can_read = True, 
                    can_write = True, 
                    can_erase = True, 
                    as_of_floor = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), ),
                body = None,
                valid_from = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                valid_to = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                edges = [
                    general_liquidity.models.remember_request_edges_inner.RememberRequest_edges_inner(
                        relation = '', 
                        to = '', )
                    ],
                source = ''
            )
        else:
            return RememberRequest(
                mandate = general_liquidity.models.memory_mandate.MemoryMandate(
                    namespace = '', 
                    can_read = True, 
                    can_write = True, 
                    can_erase = True, 
                    as_of_floor = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), ),
                valid_from = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                valid_to = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                source = '',
        )
        """

    def testRememberRequest(self):
        """Test RememberRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
