# coding: utf-8

"""
    General Liquidity: The Machine Economy API

    General Liquidity (GL) is one governed surface over payment, commerce, identity, and provenance for the machine economy. A caller submits a signed `Intent`, a deny-first gate decides, and only the server holds the settle primitive, so the caller never does. Field names are `camelCase` on the wire, identical to the spelling the typed clients use, so nothing is renamed between a client and the server that validates it. Three OUTBOUND-ONLY envelopes predate that rule and are still emitted `snake_case`: `Page`, `Job` and `WebhookEvent`. They are documented as served, and no request body carries them. 

    The version of the OpenAPI document: 2026-07-28
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from general_liquidity.models.buy_request import BuyRequest

class TestBuyRequest(unittest.TestCase):
    """BuyRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> BuyRequest:
        """Test BuyRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `BuyRequest`
        """
        model = BuyRequest()
        if include_optional:
            return BuyRequest(
                idempotency_key = '0',
                rail = 'acp',
                merchant = '0',
                currency = '0',
                lines = [
                    general_liquidity.models.commerce_line.CommerceLine(
                        id = '0', 
                        quantity = 1, )
                    ],
                purpose = '',
                terms = general_liquidity.models.terms.Terms(
                    reversibility = 'reversible', 
                    finality = 'instant', 
                    credential = '', 
                    rail = 'x402', 
                    capital_source = 'payer', 
                    presence = 'present', ),
                envelope = general_liquidity.models.envelope.Envelope(
                    identity = '', 
                    mandate_id = '', 
                    grant = general_liquidity.models.grant.Grant(
                        agent_id = '', 
                        mandate_id = '', 
                        expires_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        signature = '', ), 
                    signature = '', )
            )
        else:
            return BuyRequest(
                idempotency_key = '0',
                rail = 'acp',
                merchant = '0',
                currency = '0',
                lines = [
                    general_liquidity.models.commerce_line.CommerceLine(
                        id = '0', 
                        quantity = 1, )
                    ],
                purpose = '',
                terms = general_liquidity.models.terms.Terms(
                    reversibility = 'reversible', 
                    finality = 'instant', 
                    credential = '', 
                    rail = 'x402', 
                    capital_source = 'payer', 
                    presence = 'present', ),
                envelope = general_liquidity.models.envelope.Envelope(
                    identity = '', 
                    mandate_id = '', 
                    grant = general_liquidity.models.grant.Grant(
                        agent_id = '', 
                        mandate_id = '', 
                        expires_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        signature = '', ), 
                    signature = '', ),
        )
        """

    def testBuyRequest(self):
        """Test BuyRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
