# coding: utf-8

"""
    General Liquidity: The Machine Economy API

    General Liquidity (GL) is one governed surface over payment, commerce, identity, and provenance for the machine economy. A caller submits a signed `Intent`, a deny-first gate decides, and only the server holds the settle primitive, so the caller never does. The wire convention is `snake_case`. 

    The version of the OpenAPI document: 2026-07-26
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from general_liquidity.models.job import Job

class TestJob(unittest.TestCase):
    """Job unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Job:
        """Test Job
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Job`
        """
        model = Job()
        if include_optional:
            return Job(
                id = '',
                status = 'pending',
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                terminal_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                outcome = 'allow',
                receipt = general_liquidity.models.receipt.Receipt(
                    intent_key = '', 
                    rail = 'x402', 
                    reference = '', 
                    terms = general_liquidity.models.terms.Terms(
                        reversibility = 'reversible', 
                        finality = 'instant', 
                        credential = '', 
                        rail = 'x402', 
                        capital_source = 'payer', 
                        presence = 'present', ), 
                    settled_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    enforcement = '', ),
                problem = general_liquidity.models.problem.Problem(
                    type = 'about:blank', 
                    title = '', 
                    status = 100, 
                    detail = '', 
                    instance = '', 
                    code = '', 
                    retry_after = 56, ),
                pending = general_liquidity.models.job_pending.Job_pending(
                    mandate_id = '', 
                    challenge = '', ),
                links = general_liquidity.models.job_links.Job_links(
                    self = '', 
                    events = '', )
            )
        else:
            return Job(
                id = '',
                status = 'pending',
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                outcome = 'allow',
                links = general_liquidity.models.job_links.Job_links(
                    self = '', 
                    events = '', ),
        )
        """

    def testJob(self):
        """Test Job"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
