# coding: utf-8

"""
    General Liquidity: The Machine Economy API

    General Liquidity (GL) is one governed surface over payment, commerce, identity, and provenance for the machine economy. A caller submits a signed `Intent`, a deny-first gate decides, and only the server holds the settle primitive, so the caller never does. The wire convention is `snake_case`. 

    The version of the OpenAPI document: 2026-07-26
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from general_liquidity.models.list_webhook_endpoints200_response import ListWebhookEndpoints200Response

class TestListWebhookEndpoints200Response(unittest.TestCase):
    """ListWebhookEndpoints200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ListWebhookEndpoints200Response:
        """Test ListWebhookEndpoints200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ListWebhookEndpoints200Response`
        """
        model = ListWebhookEndpoints200Response()
        if include_optional:
            return ListWebhookEndpoints200Response(
                data = [
                    general_liquidity.models.webhook_endpoint.WebhookEndpoint(
                        id = '', 
                        url = '', 
                        events = [
                            'payment.settled'
                            ], 
                        active = True, )
                    ]
            )
        else:
            return ListWebhookEndpoints200Response(
                data = [
                    general_liquidity.models.webhook_endpoint.WebhookEndpoint(
                        id = '', 
                        url = '', 
                        events = [
                            'payment.settled'
                            ], 
                        active = True, )
                    ],
        )
        """

    def testListWebhookEndpoints200Response(self):
        """Test ListWebhookEndpoints200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
