# coding: utf-8

"""
    General Liquidity: The Machine Economy API

    General Liquidity (GL) is one governed surface over payment, commerce, identity, and provenance for the machine economy. A caller submits a signed `Intent`, a deny-first gate decides, and only the server holds the settle primitive, so the caller never does. The wire convention is `snake_case`. 

    The version of the OpenAPI document: 2026-07-23
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from general_liquidity.models.outcome import Outcome

class TestOutcome(unittest.TestCase):
    """Outcome unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testOutcome(self):
        """Test Outcome"""
        # inst = Outcome()

if __name__ == '__main__':
    unittest.main()
