# coding: utf-8

"""
    General Liquidity: The Machine Economy API

    General Liquidity (GL) is one governed surface over payment, commerce, identity, and provenance for the machine economy. A caller submits a signed `Intent`, a deny-first gate decides, and only the server holds the settle primitive, so the caller never does. The wire convention is `snake_case`. 

    The version of the OpenAPI document: 2026-07-26
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from general_liquidity.models.pending_settlement import PendingSettlement

class TestPendingSettlement(unittest.TestCase):
    """PendingSettlement unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PendingSettlement:
        """Test PendingSettlement
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PendingSettlement`
        """
        model = PendingSettlement()
        if include_optional:
            return PendingSettlement(
                type = 'clearing.pending',
                title = '',
                obligation_id = '',
                state = 'pending',
                awaiting = 'self',
                achieved_class = 'self'
            )
        else:
            return PendingSettlement(
                type = 'clearing.pending',
                title = '',
                obligation_id = '',
                state = 'pending',
                awaiting = 'self',
        )
        """

    def testPendingSettlement(self):
        """Test PendingSettlement"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
