# coding: utf-8

"""
    General Liquidity: The Machine Economy API

    General Liquidity (GL) is one governed surface over payment, commerce, identity, and provenance for the machine economy. A caller submits a signed `Intent`, a deny-first gate decides, and only the server holds the settle primitive, so the caller never does. Field names are `camelCase` on the wire, identical to the spelling the typed clients use, so nothing is renamed between a client and the server that validates it. Three OUTBOUND-ONLY envelopes predate that rule and are still emitted `snake_case`: `Page`, `Job` and `WebhookEvent`. They are documented as served, and no request body carries them. 

    The version of the OpenAPI document: 2026-07-28
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from general_liquidity.models.cart_status import CartStatus

class TestCartStatus(unittest.TestCase):
    """CartStatus unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCartStatus(self):
        """Test CartStatus"""
        # inst = CartStatus()

if __name__ == '__main__':
    unittest.main()
