# coding: utf-8

"""
    General Liquidity — The Machine Economy API

    General Liquidity (GL) is the governed, unified interface for the machine economy. A caller submits a signed `Intent`; the sovereign gate decides and only the server holds the settle primitive — the caller never reaches it (DESIGN §7, sovereign settle-separation).  This document is the **single source of truth** for the GL surface. The typed SDK (`packages/sdk`) and the MCP server (`packages/mcp`) are generated projections of this spec via Speakeasy (BUILD-PLAN §5).  Naming is canonical per `docs/NAMING.md`: verbs are single common English words (`resolve`, `pay`, `verify`, `disclose`, `buy`, `quote`); nouns are concrete singular domain objects (`Intent`, `Mandate`, `Receipt`, `Counterparty`). The wire is `snake_case`; the TypeScript SDK presents `camelCase`. Vendor/protocol names appear only as lowercase `RailId` values, never as verbs or types. 

    The version of the OpenAPI document: 2026-07-22
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from general_liquidity.models.receipt import Receipt

class TestReceipt(unittest.TestCase):
    """Receipt unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Receipt:
        """Test Receipt
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Receipt`
        """
        model = Receipt()
        if include_optional:
            return Receipt(
                intent_key = '',
                rail = 'x402',
                reference = '',
                terms = general_liquidity.models.terms.Terms(
                    reversibility = 'reversible', 
                    finality = 'instant', 
                    credential = '', 
                    rail = 'x402', 
                    capital_source = 'payer', 
                    presence = 'present', ),
                settled_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                enforcement = ''
            )
        else:
            return Receipt(
                intent_key = '',
                rail = 'x402',
                reference = '',
                terms = general_liquidity.models.terms.Terms(
                    reversibility = 'reversible', 
                    finality = 'instant', 
                    credential = '', 
                    rail = 'x402', 
                    capital_source = 'payer', 
                    presence = 'present', ),
                settled_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                enforcement = '',
        )
        """

    def testReceipt(self):
        """Test Receipt"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
