# coding: utf-8

"""
    General Liquidity: The Machine Economy API

    General Liquidity (GL) is one governed surface over payment, commerce, identity, and provenance for the machine economy. A caller submits a signed `Intent`, a deny-first gate decides, and only the server holds the settle primitive, so the caller never does. Field names are `camelCase` on the wire, identical to the spelling the typed clients use, so nothing is renamed between a client and the server that validates it. Three OUTBOUND-ONLY envelopes predate that rule and are still emitted `snake_case`: `Page`, `Job` and `WebhookEvent`. They are documented as served, and no request body carries them. 

    The version of the OpenAPI document: 2026-07-28
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from general_liquidity.models.pay202_response import Pay202Response

class TestPay202Response(unittest.TestCase):
    """Pay202Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Pay202Response:
        """Test Pay202Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Pay202Response`
        """
        model = Pay202Response()
        if include_optional:
            return Pay202Response(
                outcome = 'allow',
                reasons = [
                    ''
                    ],
                mandate_id = '',
                checks = [
                    general_liquidity.models.decision_check.DecisionCheck(
                        id = '', 
                        passed = True, )
                    ],
                type = 'clearing.pending',
                title = '',
                obligation_id = '',
                state = 'pending',
                awaiting = 'self',
                achieved_class = 'self'
            )
        else:
            return Pay202Response(
                outcome = 'allow',
                reasons = [
                    ''
                    ],
                mandate_id = '',
                type = 'clearing.pending',
                title = '',
                obligation_id = '',
                state = 'pending',
                awaiting = 'self',
        )
        """

    def testPay202Response(self):
        """Test Pay202Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
