# coding: utf-8

"""
    General Liquidity: The Machine Economy API

    General Liquidity (GL) is one governed surface over payment, commerce, identity, and provenance for the machine economy. A caller submits a signed `Intent`, a deny-first gate decides, and only the server holds the settle primitive, so the caller never does. Field names are `camelCase` on the wire, identical to the TypeScript spelling in `packages/surface`, so nothing is renamed between the typed client and the server that validates it. Three OUTBOUND-ONLY envelopes predate that rule and are still emitted `snake_case`: `Page`, `Job` and `WebhookEvent`. They are documented as served, and no request body carries them. 

    The version of the OpenAPI document: 2026-07-26
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from general_liquidity.models.disclosure import Disclosure

class TestDisclosure(unittest.TestCase):
    """Disclosure unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Disclosure:
        """Test Disclosure
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Disclosure`
        """
        model = Disclosure()
        if include_optional:
            return Disclosure(
                document = None,
                signature = general_liquidity.models.disclosure_signature.Disclosure_signature(
                    algorithm = 'ed25519', 
                    public_key = '', 
                    value = '', ),
                rotation_chain = [
                    general_liquidity.models.key_rotation_statement.KeyRotationStatement(
                        type = 'rotation', 
                        from = '', 
                        to = '', 
                        rotated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        signature = '', )
                    ]
            )
        else:
            return Disclosure(
                document = None,
                signature = general_liquidity.models.disclosure_signature.Disclosure_signature(
                    algorithm = 'ed25519', 
                    public_key = '', 
                    value = '', ),
        )
        """

    def testDisclosure(self):
        """Test Disclosure"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
