# coding: utf-8

"""
    General Liquidity: The Machine Economy API

    General Liquidity (GL) is one governed surface over payment, commerce, identity, and provenance for the machine economy. A caller submits a signed `Intent`, a deny-first gate decides, and only the server holds the settle primitive, so the caller never does. The wire convention is `snake_case`. 

    The version of the OpenAPI document: 2026-07-26
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from general_liquidity.api.webhooks_api import WebhooksApi


class TestWebhooksApi(unittest.TestCase):
    """WebhooksApi unit test stubs"""

    def setUp(self) -> None:
        self.api = WebhooksApi()

    def tearDown(self) -> None:
        pass

    def test_create_webhook_endpoint(self) -> None:
        """Test case for create_webhook_endpoint

        Register a webhook endpoint. (Operator authority)
        """
        pass

    def test_delete_webhook_endpoint(self) -> None:
        """Test case for delete_webhook_endpoint

        Delete one webhook endpoint. (Operator authority)
        """
        pass

    def test_get_webhook_endpoint(self) -> None:
        """Test case for get_webhook_endpoint

        Read one webhook endpoint. (Operator authority)
        """
        pass

    def test_list_webhook_endpoints(self) -> None:
        """Test case for list_webhook_endpoints

        List webhook endpoints. (Operator authority)
        """
        pass

    def test_update_webhook_endpoint(self) -> None:
        """Test case for update_webhook_endpoint

        Update one webhook endpoint. (Operator authority)
        """
        pass


if __name__ == '__main__':
    unittest.main()
