# coding: utf-8

"""
    General Liquidity: The Machine Economy API

    General Liquidity (GL) is one governed surface over payment, commerce, identity, and provenance for the machine economy. A caller submits a signed `Intent`, a deny-first gate decides, and only the server holds the settle primitive, so the caller never does. The wire convention is `snake_case`. 

    The version of the OpenAPI document: 2026-07-26
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from general_liquidity.models.assembled_context_budget import AssembledContextBudget

class TestAssembledContextBudget(unittest.TestCase):
    """AssembledContextBudget unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AssembledContextBudget:
        """Test AssembledContextBudget
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AssembledContextBudget`
        """
        model = AssembledContextBudget()
        if include_optional:
            return AssembledContextBudget(
                max_tokens = 56
            )
        else:
            return AssembledContextBudget(
                max_tokens = 56,
        )
        """

    def testAssembledContextBudget(self):
        """Test AssembledContextBudget"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
