# coding: utf-8

"""
    General Liquidity: The Machine Economy API

    General Liquidity (GL) is one governed surface over payment, commerce, identity, and provenance for the machine economy. A caller submits a signed `Intent`, a deny-first gate decides, and only the server holds the settle primitive, so the caller never does. Field names are `camelCase` on the wire, identical to the TypeScript spelling in `packages/surface`, so nothing is renamed between the typed client and the server that validates it. Three OUTBOUND-ONLY envelopes predate that rule and are still emitted `snake_case`: `Page`, `Job` and `WebhookEvent`. They are documented as served, and no request body carries them. 

    The version of the OpenAPI document: 2026-07-26
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from general_liquidity.models.memory_verify_request import MemoryVerifyRequest

class TestMemoryVerifyRequest(unittest.TestCase):
    """MemoryVerifyRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> MemoryVerifyRequest:
        """Test MemoryVerifyRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `MemoryVerifyRequest`
        """
        model = MemoryVerifyRequest()
        if include_optional:
            return MemoryVerifyRequest(
                artifact = None
            )
        else:
            return MemoryVerifyRequest(
                artifact = None,
        )
        """

    def testMemoryVerifyRequest(self):
        """Test MemoryVerifyRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
