# coding: utf-8

"""
    General Liquidity: The Machine Economy API

    General Liquidity (GL) is one governed surface over payment, commerce, identity, and provenance for the machine economy. A caller submits a signed `Intent`, a deny-first gate decides, and only the server holds the settle primitive, so the caller never does. The wire convention is `snake_case`. 

    The version of the OpenAPI document: 2026-07-25
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from general_liquidity.models.mandate import Mandate

class TestMandate(unittest.TestCase):
    """Mandate unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Mandate:
        """Test Mandate
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Mandate`
        """
        model = Mandate()
        if include_optional:
            return Mandate(
                id = '',
                payees = [
                    ''
                    ],
                per_tx_cap = general_liquidity.models.amount.Amount(
                    value = '', 
                    asset = '', ),
                per_period_cap = general_liquidity.models.amount.Amount(
                    value = '', 
                    asset = '', ),
                period = '',
                expires_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                constraints = {
                    'key' : null
                    }
            )
        else:
            return Mandate(
                id = '',
                payees = [
                    ''
                    ],
                per_tx_cap = general_liquidity.models.amount.Amount(
                    value = '', 
                    asset = '', ),
                per_period_cap = general_liquidity.models.amount.Amount(
                    value = '', 
                    asset = '', ),
                period = '',
                expires_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
        )
        """

    def testMandate(self):
        """Test Mandate"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
