# coding: utf-8

"""
    General Liquidity: The Machine Economy API

    One governed surface over payment, commerce, identity, and provenance for
    the machine economy. A caller submits a signed Intent, a deny-first gate
    decides, and only the server holds the settle primitive, so the caller
    never does. The wire convention is snake_case.

    The version of the OpenAPI document: 2026-07-22
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from setuptools import setup, find_packages  # noqa: H301

# To install the library, run the following
#
# python setup.py install
#
# prerequisite: setuptools
# http://pypi.python.org/pypi/setuptools
NAME = "general-liquidity"
VERSION = "1.0.0"
PYTHON_REQUIRES = ">= 3.8"
REQUIRES = [
    "urllib3 >= 1.25.3, < 3.0.0",
    "python-dateutil >= 2.8.2",
    "pydantic >= 2",
    "typing-extensions >= 4.7.1",
]

setup(
    name=NAME,
    version=VERSION,
    description="General Liquidity: The Machine Economy API",
    author="General Liquidity",
    author_email="",
    url="https://github.com/general-liquidity/general-liquidity-python",
    keywords=["OpenAPI", "OpenAPI-Generator", "General Liquidity"],
    install_requires=REQUIRES,
    package_dir={"": "src"},
    packages=find_packages(where="src", exclude=["test", "tests"]),
    include_package_data=True,
    license="MIT",
    long_description_content_type='text/markdown',
    long_description="""\
    One governed surface over payment, commerce, identity, and provenance for the machine economy. A caller submits a signed Intent, a deny-first gate decides, and only the server holds the settle primitive, so the caller never does. The wire convention is snake_case.
    """,  # noqa: E501
    package_data={"general_liquidity": ["py.typed"]},
)
