# coding: utf-8

"""
    General Liquidity — The Machine Economy API

    General Liquidity (GL) is the governed, unified interface for the machine economy. A caller submits a signed `Intent`; the sovereign gate decides and only the server holds the settle primitive — the caller never reaches it (DESIGN §7, sovereign settle-separation).  This document is the **single source of truth** for the GL surface. The typed SDK (`packages/sdk`) and the MCP server (`packages/mcp`) are generated projections of this spec via Speakeasy (BUILD-PLAN §5).  Naming is canonical per `docs/NAMING.md`: verbs are single common English words (`resolve`, `pay`, `verify`, `disclose`, `buy`, `quote`); nouns are concrete singular domain objects (`Intent`, `Mandate`, `Receipt`, `Counterparty`). The wire is `snake_case`; the TypeScript SDK presents `camelCase`. Vendor/protocol names appear only as lowercase `RailId` values, never as verbs or types. 

    The version of the OpenAPI document: 2026-07-22
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from setuptools import setup, find_packages  # noqa: H301

# To install the library, run the following
#
# python setup.py install
#
# prerequisite: setuptools
# http://pypi.python.org/pypi/setuptools
NAME = "general-liquidity"
VERSION = "1.0.0"
PYTHON_REQUIRES = ">= 3.8"
REQUIRES = [
    "urllib3 >= 1.25.3, < 3.0.0",
    "python-dateutil >= 2.8.2",
    "pydantic >= 2",
    "typing-extensions >= 4.7.1",
]

setup(
    name=NAME,
    version=VERSION,
    description="General Liquidity — The Machine Economy API",
    author="General Liquidity",
    author_email="team@openapitools.org",
    url="",
    keywords=["OpenAPI", "OpenAPI-Generator", "General Liquidity — The Machine Economy API"],
    install_requires=REQUIRES,
    packages=find_packages(exclude=["test", "tests"]),
    include_package_data=True,
    license="Apache-2.0",
    long_description_content_type='text/markdown',
    long_description="""\
    General Liquidity (GL) is the governed, unified interface for the machine economy. A caller submits a signed &#x60;Intent&#x60;; the sovereign gate decides and only the server holds the settle primitive — the caller never reaches it (DESIGN §7, sovereign settle-separation).  This document is the **single source of truth** for the GL surface. The typed SDK (&#x60;packages/sdk&#x60;) and the MCP server (&#x60;packages/mcp&#x60;) are generated projections of this spec via Speakeasy (BUILD-PLAN §5).  Naming is canonical per &#x60;docs/NAMING.md&#x60;: verbs are single common English words (&#x60;resolve&#x60;, &#x60;pay&#x60;, &#x60;verify&#x60;, &#x60;disclose&#x60;, &#x60;buy&#x60;, &#x60;quote&#x60;); nouns are concrete singular domain objects (&#x60;Intent&#x60;, &#x60;Mandate&#x60;, &#x60;Receipt&#x60;, &#x60;Counterparty&#x60;). The wire is &#x60;snake_case&#x60;; the TypeScript SDK presents &#x60;camelCase&#x60;. Vendor/protocol names appear only as lowercase &#x60;RailId&#x60; values, never as verbs or types. 
    """,  # noqa: E501
    package_data={"general_liquidity": ["py.typed"]},
)