# coding: utf-8

"""
    General Liquidity — The Machine Economy API

    General Liquidity (GL) is the governed, unified interface for the machine economy. A caller submits a signed `Intent`; the sovereign gate decides and only the server holds the settle primitive — the caller never reaches it (DESIGN §7, sovereign settle-separation).  This document is the **single source of truth** for the GL surface. The typed SDK (`packages/sdk`) and the MCP server (`packages/mcp`) are generated projections of this spec via Speakeasy (BUILD-PLAN §5).  Naming is canonical per `docs/NAMING.md`: verbs are single common English words (`resolve`, `pay`, `verify`, `disclose`, `buy`, `quote`); nouns are concrete singular domain objects (`Intent`, `Mandate`, `Receipt`, `Counterparty`). The wire is `snake_case`; the TypeScript SDK presents `camelCase`. Vendor/protocol names appear only as lowercase `RailId` values, never as verbs or types. 

    The version of the OpenAPI document: 2026-07-22
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictStr
from typing import Any, ClassVar, Dict, List
from general_liquidity.models.outcome import Outcome
from typing import Optional, Set
from typing_extensions import Self

class Decision(BaseModel):
    """
    The gate's decision on an Intent.
    """ # noqa: E501
    outcome: Outcome
    reasons: List[StrictStr]
    mandate_id: StrictStr
    __properties: ClassVar[List[str]] = ["outcome", "reasons", "mandate_id"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of Decision from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of Decision from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "outcome": obj.get("outcome"),
            "reasons": obj.get("reasons"),
            "mandate_id": obj.get("mandate_id")
        })
        return _obj


