# coding: utf-8

"""
    General Liquidity: The Machine Economy API

    General Liquidity (GL) is one governed surface over payment, commerce, identity, and provenance for the machine economy. A caller submits a signed `Intent`, a deny-first gate decides, and only the server holds the settle primitive, so the caller never does. Field names are `camelCase` on the wire, identical to the spelling the typed clients use, so nothing is renamed between a client and the server that validates it. Three OUTBOUND-ONLY envelopes predate that rule and are still emitted `snake_case`: `Page`, `Job` and `WebhookEvent`. They are documented as served, and no request body carries them. 

    The version of the OpenAPI document: 2026-07-28
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501

import warnings
from pydantic import validate_call, Field, StrictFloat, StrictStr, StrictInt
from typing import Any, Dict, List, Optional, Tuple, Union
from typing_extensions import Annotated

from general_liquidity.models.buy_request import BuyRequest
from general_liquidity.models.cart import Cart
from general_liquidity.models.order import Order
from general_liquidity.models.quote_request import QuoteRequest

from general_liquidity.api_client import ApiClient, RequestSerialized
from general_liquidity.api_response import ApiResponse
from general_liquidity.rest import RESTResponseType


class CommerceApi:
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    def __init__(self, api_client=None) -> None:
        if api_client is None:
            api_client = ApiClient.get_default()
        self.api_client = api_client


    @validate_call
    def buy(
        self,
        buy_request: BuyRequest,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> Order:
        """Drive a merchant checkout to a completed Order.

        Drive a merchant checkout to `ready`, authorize it through the SAME gate `/pay` uses, and return the completed `Order` carrying the settlement `Receipt`. The merchant stays merchant-of-record. The PRICE is never taken from the caller: it comes from the server-authoritative `Cart` the merchant priced, so this body carries lines, not amounts. The caller holds no settle primitive here either — the engine behind this route is built over the gateway's own gated `pay` and cannot reach a rail any other way.  OPT-IN, DEFAULT-OFF. Served only where the deployment enabled the commerce tier (`StackConfig.commerce: true`); a deployment that did not answers `404 not_found` on this path exactly as if it never existed.  Because it settles, it is under the same fail-closed rule as `/pay`: where the route exists and no authentication is configured, it refuses rather than settling. Replay is server-side and keyed on the body's `idempotencyKey`, namespaced separately from `/pay`'s. A `503 rail.unavailable` is retryable by construction and is the one outcome NOT stored, so the identical request may be re-sent under the same key. 

        :param buy_request: (required)
        :type buy_request: BuyRequest
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._buy_serialize(
            buy_request=buy_request,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "Order",
            '400': "Problem",
            '401': "Problem",
            '403': "Problem",
            '404': "Problem",
            '429': "Problem",
            '500': "Problem",
            '503': "Problem",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        ).data


    @validate_call
    def buy_with_http_info(
        self,
        buy_request: BuyRequest,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> ApiResponse[Order]:
        """Drive a merchant checkout to a completed Order.

        Drive a merchant checkout to `ready`, authorize it through the SAME gate `/pay` uses, and return the completed `Order` carrying the settlement `Receipt`. The merchant stays merchant-of-record. The PRICE is never taken from the caller: it comes from the server-authoritative `Cart` the merchant priced, so this body carries lines, not amounts. The caller holds no settle primitive here either — the engine behind this route is built over the gateway's own gated `pay` and cannot reach a rail any other way.  OPT-IN, DEFAULT-OFF. Served only where the deployment enabled the commerce tier (`StackConfig.commerce: true`); a deployment that did not answers `404 not_found` on this path exactly as if it never existed.  Because it settles, it is under the same fail-closed rule as `/pay`: where the route exists and no authentication is configured, it refuses rather than settling. Replay is server-side and keyed on the body's `idempotencyKey`, namespaced separately from `/pay`'s. A `503 rail.unavailable` is retryable by construction and is the one outcome NOT stored, so the identical request may be re-sent under the same key. 

        :param buy_request: (required)
        :type buy_request: BuyRequest
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._buy_serialize(
            buy_request=buy_request,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "Order",
            '400': "Problem",
            '401': "Problem",
            '403': "Problem",
            '404': "Problem",
            '429': "Problem",
            '500': "Problem",
            '503': "Problem",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        )


    @validate_call
    def buy_without_preload_content(
        self,
        buy_request: BuyRequest,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> RESTResponseType:
        """Drive a merchant checkout to a completed Order.

        Drive a merchant checkout to `ready`, authorize it through the SAME gate `/pay` uses, and return the completed `Order` carrying the settlement `Receipt`. The merchant stays merchant-of-record. The PRICE is never taken from the caller: it comes from the server-authoritative `Cart` the merchant priced, so this body carries lines, not amounts. The caller holds no settle primitive here either — the engine behind this route is built over the gateway's own gated `pay` and cannot reach a rail any other way.  OPT-IN, DEFAULT-OFF. Served only where the deployment enabled the commerce tier (`StackConfig.commerce: true`); a deployment that did not answers `404 not_found` on this path exactly as if it never existed.  Because it settles, it is under the same fail-closed rule as `/pay`: where the route exists and no authentication is configured, it refuses rather than settling. Replay is server-side and keyed on the body's `idempotencyKey`, namespaced separately from `/pay`'s. A `503 rail.unavailable` is retryable by construction and is the one outcome NOT stored, so the identical request may be re-sent under the same key. 

        :param buy_request: (required)
        :type buy_request: BuyRequest
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._buy_serialize(
            buy_request=buy_request,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "Order",
            '400': "Problem",
            '401': "Problem",
            '403': "Problem",
            '404': "Problem",
            '429': "Problem",
            '500': "Problem",
            '503': "Problem",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        return response_data.response


    def _buy_serialize(
        self,
        buy_request,
        _request_auth,
        _content_type,
        _headers,
        _host_index,
    ) -> RequestSerialized:

        _host = None

        _collection_formats: Dict[str, str] = {
        }

        _path_params: Dict[str, str] = {}
        _query_params: List[Tuple[str, str]] = []
        _header_params: Dict[str, Optional[str]] = _headers or {}
        _form_params: List[Tuple[str, str]] = []
        _files: Dict[
            str, Union[str, bytes, List[str], List[bytes], List[Tuple[str, bytes]]]
        ] = {}
        _body_params: Optional[bytes] = None

        # process the path parameters
        # process the query parameters
        # process the header parameters
        # process the form parameters
        # process the body parameter
        if buy_request is not None:
            _body_params = buy_request


        # set the HTTP header `Accept`
        if 'Accept' not in _header_params:
            _header_params['Accept'] = self.api_client.select_header_accept(
                [
                    'application/json', 
                    'application/problem+json'
                ]
            )

        # set the HTTP header `Content-Type`
        if _content_type:
            _header_params['Content-Type'] = _content_type
        else:
            _default_content_type = (
                self.api_client.select_header_content_type(
                    [
                        'application/json'
                    ]
                )
            )
            if _default_content_type is not None:
                _header_params['Content-Type'] = _default_content_type

        # authentication setting
        _auth_settings: List[str] = [
            'bearerAuth'
        ]

        return self.api_client.param_serialize(
            method='POST',
            resource_path='/buy',
            path_params=_path_params,
            query_params=_query_params,
            header_params=_header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            auth_settings=_auth_settings,
            collection_formats=_collection_formats,
            _host=_host,
            _request_auth=_request_auth
        )




    @validate_call
    def quote(
        self,
        quote_request: QuoteRequest,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> Cart:
        """Price a cart against a merchant. Commits nothing.

        Get a server-authoritative priced `Cart` — the merchant computes tax, inventory and fulfillment — before committing to `buy`. Moves no money and holds no value, so it is an ordinary agent read on the bearer credential.  OPT-IN, DEFAULT-OFF. Served only where the deployment enabled the commerce tier (`StackConfig.commerce: true`); a deployment that did not answers `404 not_found` on this path exactly as if it never existed. Enabling it is a deployment decision because it opens an outbound HTTP path to arbitrary merchants. 

        :param quote_request: (required)
        :type quote_request: QuoteRequest
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._quote_serialize(
            quote_request=quote_request,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "Cart",
            '400': "Problem",
            '401': "Problem",
            '403': "Problem",
            '404': "Problem",
            '429': "Problem",
            '503': "Problem",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        ).data


    @validate_call
    def quote_with_http_info(
        self,
        quote_request: QuoteRequest,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> ApiResponse[Cart]:
        """Price a cart against a merchant. Commits nothing.

        Get a server-authoritative priced `Cart` — the merchant computes tax, inventory and fulfillment — before committing to `buy`. Moves no money and holds no value, so it is an ordinary agent read on the bearer credential.  OPT-IN, DEFAULT-OFF. Served only where the deployment enabled the commerce tier (`StackConfig.commerce: true`); a deployment that did not answers `404 not_found` on this path exactly as if it never existed. Enabling it is a deployment decision because it opens an outbound HTTP path to arbitrary merchants. 

        :param quote_request: (required)
        :type quote_request: QuoteRequest
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._quote_serialize(
            quote_request=quote_request,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "Cart",
            '400': "Problem",
            '401': "Problem",
            '403': "Problem",
            '404': "Problem",
            '429': "Problem",
            '503': "Problem",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        )


    @validate_call
    def quote_without_preload_content(
        self,
        quote_request: QuoteRequest,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> RESTResponseType:
        """Price a cart against a merchant. Commits nothing.

        Get a server-authoritative priced `Cart` — the merchant computes tax, inventory and fulfillment — before committing to `buy`. Moves no money and holds no value, so it is an ordinary agent read on the bearer credential.  OPT-IN, DEFAULT-OFF. Served only where the deployment enabled the commerce tier (`StackConfig.commerce: true`); a deployment that did not answers `404 not_found` on this path exactly as if it never existed. Enabling it is a deployment decision because it opens an outbound HTTP path to arbitrary merchants. 

        :param quote_request: (required)
        :type quote_request: QuoteRequest
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._quote_serialize(
            quote_request=quote_request,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "Cart",
            '400': "Problem",
            '401': "Problem",
            '403': "Problem",
            '404': "Problem",
            '429': "Problem",
            '503': "Problem",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        return response_data.response


    def _quote_serialize(
        self,
        quote_request,
        _request_auth,
        _content_type,
        _headers,
        _host_index,
    ) -> RequestSerialized:

        _host = None

        _collection_formats: Dict[str, str] = {
        }

        _path_params: Dict[str, str] = {}
        _query_params: List[Tuple[str, str]] = []
        _header_params: Dict[str, Optional[str]] = _headers or {}
        _form_params: List[Tuple[str, str]] = []
        _files: Dict[
            str, Union[str, bytes, List[str], List[bytes], List[Tuple[str, bytes]]]
        ] = {}
        _body_params: Optional[bytes] = None

        # process the path parameters
        # process the query parameters
        # process the header parameters
        # process the form parameters
        # process the body parameter
        if quote_request is not None:
            _body_params = quote_request


        # set the HTTP header `Accept`
        if 'Accept' not in _header_params:
            _header_params['Accept'] = self.api_client.select_header_accept(
                [
                    'application/json', 
                    'application/problem+json'
                ]
            )

        # set the HTTP header `Content-Type`
        if _content_type:
            _header_params['Content-Type'] = _content_type
        else:
            _default_content_type = (
                self.api_client.select_header_content_type(
                    [
                        'application/json'
                    ]
                )
            )
            if _default_content_type is not None:
                _header_params['Content-Type'] = _default_content_type

        # authentication setting
        _auth_settings: List[str] = [
            'bearerAuth'
        ]

        return self.api_client.param_serialize(
            method='POST',
            resource_path='/quote',
            path_params=_path_params,
            query_params=_query_params,
            header_params=_header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            auth_settings=_auth_settings,
            collection_formats=_collection_formats,
            _host=_host,
            _request_auth=_request_auth
        )


