# coding: utf-8

"""
    General Liquidity: The Machine Economy API

    General Liquidity (GL) is one governed surface over payment, commerce, identity, and provenance for the machine economy. A caller submits a signed `Intent`, a deny-first gate decides, and only the server holds the settle primitive, so the caller never does. Field names are `camelCase` on the wire, identical to the spelling the typed clients use, so nothing is renamed between a client and the server that validates it. Three OUTBOUND-ONLY envelopes predate that rule and are still emitted `snake_case`: `Page`, `Job` and `WebhookEvent`. They are documented as served, and no request body carries them. 

    The version of the OpenAPI document: 2026-07-28
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from general_liquidity.models.assemble_request_recall import AssembleRequestRecall
from general_liquidity.models.assembled_context_budget import AssembledContextBudget
from general_liquidity.models.memory_mandate import MemoryMandate
from general_liquidity.models.snapshot import Snapshot
from typing import Optional, Set
from typing_extensions import Self

class AssembleRequest(BaseModel):
    """
    Budgeted context assembly over a supplied snapshot OR recall params.
    """ # noqa: E501
    mandate: MemoryMandate
    snapshot: Optional[Snapshot] = None
    recall: Optional[AssembleRequestRecall] = None
    budget: AssembledContextBudget
    namespace: Optional[StrictStr] = None
    __properties: ClassVar[List[str]] = ["mandate", "snapshot", "recall", "budget", "namespace"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of AssembleRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of mandate
        if self.mandate:
            _dict['mandate'] = self.mandate.to_dict()
        # override the default output from pydantic by calling `to_dict()` of snapshot
        if self.snapshot:
            _dict['snapshot'] = self.snapshot.to_dict()
        # override the default output from pydantic by calling `to_dict()` of recall
        if self.recall:
            _dict['recall'] = self.recall.to_dict()
        # override the default output from pydantic by calling `to_dict()` of budget
        if self.budget:
            _dict['budget'] = self.budget.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of AssembleRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "mandate": MemoryMandate.from_dict(obj["mandate"]) if obj.get("mandate") is not None else None,
            "snapshot": Snapshot.from_dict(obj["snapshot"]) if obj.get("snapshot") is not None else None,
            "recall": AssembleRequestRecall.from_dict(obj["recall"]) if obj.get("recall") is not None else None,
            "budget": AssembledContextBudget.from_dict(obj["budget"]) if obj.get("budget") is not None else None,
            "namespace": obj.get("namespace")
        })
        return _obj


