# coding: utf-8

"""
    General Liquidity: The Machine Economy API

    General Liquidity (GL) is one governed surface over payment, commerce, identity, and provenance for the machine economy. A caller submits a signed `Intent`, a deny-first gate decides, and only the server holds the settle primitive, so the caller never does. The wire convention is `snake_case`. 

    The version of the OpenAPI document: 2026-07-25
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from general_liquidity.models.assembled_context_budget import AssembledContextBudget
from general_liquidity.models.memory_record import MemoryRecord
from general_liquidity.models.seal import Seal
from typing import Optional, Set
from typing_extensions import Self

class AssembledContext(BaseModel):
    """
    A budgeted, ordered context assembled from a snapshot, under one seal. Abstention (`abstained: true`) is a valid result — the engine declining to fill the budget. 
    """ # noqa: E501
    records: List[MemoryRecord]
    order: List[StrictStr]
    budget: AssembledContextBudget
    abstained: StrictBool
    abstain_reason: Optional[StrictStr] = Field(default=None, alias="abstainReason")
    seal: Seal
    __properties: ClassVar[List[str]] = ["records", "order", "budget", "abstained", "abstainReason", "seal"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of AssembledContext from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in records (list)
        _items = []
        if self.records:
            for _item_records in self.records:
                if _item_records:
                    _items.append(_item_records.to_dict())
            _dict['records'] = _items
        # override the default output from pydantic by calling `to_dict()` of budget
        if self.budget:
            _dict['budget'] = self.budget.to_dict()
        # override the default output from pydantic by calling `to_dict()` of seal
        if self.seal:
            _dict['seal'] = self.seal.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of AssembledContext from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "records": [MemoryRecord.from_dict(_item) for _item in obj["records"]] if obj.get("records") is not None else None,
            "order": obj.get("order"),
            "budget": AssembledContextBudget.from_dict(obj["budget"]) if obj.get("budget") is not None else None,
            "abstained": obj.get("abstained"),
            "abstainReason": obj.get("abstainReason"),
            "seal": Seal.from_dict(obj["seal"]) if obj.get("seal") is not None else None
        })
        return _obj


