# coding: utf-8

"""
    General Liquidity: The Machine Economy API

    General Liquidity (GL) is one governed surface over payment, commerce, identity, and provenance for the machine economy. A caller submits a signed `Intent`, a deny-first gate decides, and only the server holds the settle primitive, so the caller never does. Field names are `camelCase` on the wire, identical to the spelling the typed clients use, so nothing is renamed between a client and the server that validates it. Three OUTBOUND-ONLY envelopes predate that rule and are still emitted `snake_case`: `Page`, `Job` and `WebhookEvent`. They are documented as served, and no request body carries them. 

    The version of the OpenAPI document: 2026-07-28
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class CartStatus(str, Enum):
    """
    The normalized checkout lifecycle. Only `ready` may be authorized; the rest are the states a refusal reports. 
    """

    """
    allowed enum values
    """
    PRICED = 'priced'
    ESCALATION_REQUIRED = 'escalation_required'
    READY = 'ready'
    AUTHORIZED = 'authorized'
    COMPLETED = 'completed'
    CANCELED = 'canceled'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of CartStatus from a JSON string"""
        return cls(json.loads(json_str))


