# coding: utf-8

"""
    General Liquidity: The Machine Economy API

    General Liquidity (GL) is one governed surface over payment, commerce, identity, and provenance for the machine economy. A caller submits a signed `Intent`, a deny-first gate decides, and only the server holds the settle primitive, so the caller never does. Field names are `camelCase` on the wire, identical to the spelling the typed clients use, so nothing is renamed between a client and the server that validates it. Three OUTBOUND-ONLY envelopes predate that rule and are still emitted `snake_case`: `Page`, `Job` and `WebhookEvent`. They are documented as served, and no request body carries them. 

    The version of the OpenAPI document: 2026-07-28
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List
from general_liquidity.models.amount import Amount
from general_liquidity.models.envelope import Envelope
from general_liquidity.models.terms import Terms
from typing import Optional, Set
from typing_extensions import Self

class Intent(BaseModel):
    """
    A signed request to move value. Input to pay(); never carries a settle primitive.
    """ # noqa: E501
    idempotency_key: StrictStr = Field(alias="idempotencyKey")
    payee: StrictStr = Field(description="Resolved to a CAIP-10 account where the rail is on-chain.")
    amount: Amount
    purpose: StrictStr
    terms: Terms
    envelope: Envelope
    __properties: ClassVar[List[str]] = ["idempotencyKey", "payee", "amount", "purpose", "terms", "envelope"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of Intent from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of amount
        if self.amount:
            _dict['amount'] = self.amount.to_dict()
        # override the default output from pydantic by calling `to_dict()` of terms
        if self.terms:
            _dict['terms'] = self.terms.to_dict()
        # override the default output from pydantic by calling `to_dict()` of envelope
        if self.envelope:
            _dict['envelope'] = self.envelope.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of Intent from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "idempotencyKey": obj.get("idempotencyKey"),
            "payee": obj.get("payee"),
            "amount": Amount.from_dict(obj["amount"]) if obj.get("amount") is not None else None,
            "purpose": obj.get("purpose"),
            "terms": Terms.from_dict(obj["terms"]) if obj.get("terms") is not None else None,
            "envelope": Envelope.from_dict(obj["envelope"]) if obj.get("envelope") is not None else None
        })
        return _obj


