# coding: utf-8

"""
    General Liquidity: The Machine Economy API

    General Liquidity (GL) is one governed surface over payment, commerce, identity, and provenance for the machine economy. A caller submits a signed `Intent`, a deny-first gate decides, and only the server holds the settle primitive, so the caller never does. The wire convention is `snake_case`. 

    The version of the OpenAPI document: 2026-07-25
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from general_liquidity.models.job_links import JobLinks
from general_liquidity.models.job_pending import JobPending
from general_liquidity.models.job_status import JobStatus
from general_liquidity.models.outcome import Outcome
from general_liquidity.models.problem import Problem
from general_liquidity.models.receipt import Receipt
from typing import Optional, Set
from typing_extensions import Self

class Job(BaseModel):
    """
    A read projection over an intent's confirm-park-approve lifecycle.
    """ # noqa: E501
    id: StrictStr = Field(description="The idempotency/intent key — the stable resource id.")
    status: JobStatus
    created_at: datetime = Field(description="The intent's first audit entry, falling back to its settle time.")
    terminal_at: Optional[datetime] = Field(default=None, description="Set ONLY for terminal states (settled/denied/failed).")
    outcome: Outcome
    receipt: Optional[Receipt] = None
    problem: Optional[Problem] = None
    pending: Optional[JobPending] = None
    links: JobLinks
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = ["id", "status", "created_at", "terminal_at", "outcome", "receipt", "problem", "pending", "links"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of Job from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set([
            "additional_properties",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of receipt
        if self.receipt:
            _dict['receipt'] = self.receipt.to_dict()
        # override the default output from pydantic by calling `to_dict()` of problem
        if self.problem:
            _dict['problem'] = self.problem.to_dict()
        # override the default output from pydantic by calling `to_dict()` of pending
        if self.pending:
            _dict['pending'] = self.pending.to_dict()
        # override the default output from pydantic by calling `to_dict()` of links
        if self.links:
            _dict['links'] = self.links.to_dict()
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of Job from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "status": obj.get("status"),
            "created_at": obj.get("created_at"),
            "terminal_at": obj.get("terminal_at"),
            "outcome": obj.get("outcome"),
            "receipt": Receipt.from_dict(obj["receipt"]) if obj.get("receipt") is not None else None,
            "problem": Problem.from_dict(obj["problem"]) if obj.get("problem") is not None else None,
            "pending": JobPending.from_dict(obj["pending"]) if obj.get("pending") is not None else None,
            "links": JobLinks.from_dict(obj["links"]) if obj.get("links") is not None else None
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj


