# coding: utf-8

"""
    General Liquidity: The Machine Economy API

    General Liquidity (GL) is one governed surface over payment, commerce, identity, and provenance for the machine economy. A caller submits a signed `Intent`, a deny-first gate decides, and only the server holds the settle primitive, so the caller never does. The wire convention is `snake_case`. 

    The version of the OpenAPI document: 2026-07-24
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from general_liquidity.models.amount import Amount
from typing import Optional, Set
from typing_extensions import Self

class Mandate(BaseModel):
    """
    Operator-granted, scoped, capped, expiring spend authority.
    """ # noqa: E501
    id: StrictStr
    payees: List[StrictStr] = Field(description="Allowed counterparties (CAIP-10 where on-chain).")
    per_tx_cap: Amount
    per_period_cap: Amount
    period: StrictStr = Field(description="ISO-8601 duration for the period cap window.")
    expires_at: datetime
    constraints: Optional[Dict[str, Any]] = None
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = ["id", "payees", "per_tx_cap", "per_period_cap", "period", "expires_at", "constraints"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of Mandate from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set([
            "additional_properties",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of per_tx_cap
        if self.per_tx_cap:
            _dict['per_tx_cap'] = self.per_tx_cap.to_dict()
        # override the default output from pydantic by calling `to_dict()` of per_period_cap
        if self.per_period_cap:
            _dict['per_period_cap'] = self.per_period_cap.to_dict()
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of Mandate from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "payees": obj.get("payees"),
            "per_tx_cap": Amount.from_dict(obj["per_tx_cap"]) if obj.get("per_tx_cap") is not None else None,
            "per_period_cap": Amount.from_dict(obj["per_period_cap"]) if obj.get("per_period_cap") is not None else None,
            "period": obj.get("period"),
            "expires_at": obj.get("expires_at"),
            "constraints": obj.get("constraints")
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj


