# coding: utf-8

"""
    General Liquidity: The Machine Economy API

    General Liquidity (GL) is one governed surface over payment, commerce, identity, and provenance for the machine economy. A caller submits a signed `Intent`, a deny-first gate decides, and only the server holds the settle primitive, so the caller never does. The wire convention is `snake_case`. 

    The version of the OpenAPI document: 2026-07-26
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr
from typing import Any, ClassVar, Dict, List
from typing_extensions import Annotated
from typing import Optional, Set
from typing_extensions import Self

class OperatorApprove(BaseModel):
    """
    Resume material for a parked intent, exactly as carried on an `approval.pending` problem, plus the operator's rationale and challenge-response acknowledgement. 
    """ # noqa: E501
    intent_id: StrictStr = Field(description="The parked intent id.")
    challenge: StrictStr = Field(description="The opaque challenge that binds this approval to that intent. Not a bearer credential.")
    mandate_id: StrictStr = Field(description="The mandate the gate matched when it parked the intent.")
    rationale: Annotated[str, Field(min_length=10, strict=True)] = Field(description="Why the operator is releasing it. Recorded in the signed audit chain.")
    acknowledged: StrictBool = Field(description="Explicit challenge-response acknowledgement. Never inferred: a high-risk, irreversible or large intent is not released unless this is `true`. ")
    __properties: ClassVar[List[str]] = ["intent_id", "challenge", "mandate_id", "rationale", "acknowledged"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of OperatorApprove from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of OperatorApprove from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "intent_id": obj.get("intent_id"),
            "challenge": obj.get("challenge"),
            "mandate_id": obj.get("mandate_id"),
            "rationale": obj.get("rationale"),
            "acknowledged": obj.get("acknowledged")
        })
        return _obj


