# coding: utf-8

"""
    General Liquidity: The Machine Economy API

    General Liquidity (GL) is one governed surface over payment, commerce, identity, and provenance for the machine economy. A caller submits a signed `Intent`, a deny-first gate decides, and only the server holds the settle primitive, so the caller never does. Field names are `camelCase` on the wire, identical to the spelling the typed clients use, so nothing is renamed between a client and the server that validates it. Three OUTBOUND-ONLY envelopes predate that rule and are still emitted `snake_case`: `Page`, `Job` and `WebhookEvent`. They are documented as served, and no request body carries them. 

    The version of the OpenAPI document: 2026-07-28
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List
from general_liquidity.models.cart_status import CartStatus
from general_liquidity.models.receipt import Receipt
from typing import Optional, Set
from typing_extensions import Self

class Order(BaseModel):
    """
    A completed purchase, as `buy` returns it. The merchant stays merchant-of-record; GL supplied the gated settlement and the receipt that proves it. 
    """ # noqa: E501
    id: StrictStr
    cart_id: StrictStr = Field(description="The cart this order was placed from.", alias="cartId")
    protocol: StrictStr
    status: CartStatus
    merchant: StrictStr
    receipt: Receipt = Field(description="The settlement Receipt the gated `pay` produced for the authorize beat.")
    placed_at: datetime = Field(alias="placedAt")
    __properties: ClassVar[List[str]] = ["id", "cartId", "protocol", "status", "merchant", "receipt", "placedAt"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of Order from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of receipt
        if self.receipt:
            _dict['receipt'] = self.receipt.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of Order from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "cartId": obj.get("cartId"),
            "protocol": obj.get("protocol"),
            "status": obj.get("status"),
            "merchant": obj.get("merchant"),
            "receipt": Receipt.from_dict(obj["receipt"]) if obj.get("receipt") is not None else None,
            "placedAt": obj.get("placedAt")
        })
        return _obj


