# coding: utf-8

"""
    General Liquidity: The Machine Economy API

    General Liquidity (GL) is one governed surface over payment, commerce, identity, and provenance for the machine economy. A caller submits a signed `Intent`, a deny-first gate decides, and only the server holds the settle primitive, so the caller never does. Field names are `camelCase` on the wire, identical to the TypeScript spelling in `packages/surface`, so nothing is renamed between the typed client and the server that validates it. Three OUTBOUND-ONLY envelopes predate that rule and are still emitted `snake_case`: `Page`, `Job` and `WebhookEvent`. They are documented as served, and no request body carries them. 

    The version of the OpenAPI document: 2026-07-26
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class Outcome(str, Enum):
    """
    The gate's verdict. Deny-first.
    """

    """
    allowed enum values
    """
    ALLOW = 'allow'
    CONFIRM = 'confirm'
    DENY = 'deny'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of Outcome from a JSON string"""
        return cls(json.loads(json_str))


