# coding: utf-8

"""
    General Liquidity: The Machine Economy API

    General Liquidity (GL) is one governed surface over payment, commerce, identity, and provenance for the machine economy. A caller submits a signed `Intent`, a deny-first gate decides, and only the server holds the settle primitive, so the caller never does. Field names are `camelCase` on the wire, identical to the spelling the typed clients use, so nothing is renamed between a client and the server that validates it. Three OUTBOUND-ONLY envelopes predate that rule and are still emitted `snake_case`: `Page`, `Job` and `WebhookEvent`. They are documented as served, and no request body carries them. 

    The version of the OpenAPI document: 2026-07-28
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
import pprint
from pydantic import BaseModel, ConfigDict, Field, StrictStr, ValidationError, field_validator
from typing import Any, List, Optional
from general_liquidity.models.decision import Decision
from general_liquidity.models.pending_settlement import PendingSettlement
from pydantic import StrictStr, Field
from typing import Union, List, Set, Optional, Dict
from typing_extensions import Literal, Self

PAY202RESPONSE_ONE_OF_SCHEMAS = ["Decision", "PendingSettlement"]

class Pay202Response(BaseModel):
    """
    Pay202Response
    """
    # data type: Decision
    oneof_schema_1_validator: Optional[Decision] = None
    # data type: PendingSettlement
    oneof_schema_2_validator: Optional[PendingSettlement] = None
    actual_instance: Optional[Union[Decision, PendingSettlement]] = None
    one_of_schemas: Set[str] = { "Decision", "PendingSettlement" }

    model_config = ConfigDict(
        validate_assignment=True,
        protected_namespaces=(),
    )


    def __init__(self, *args, **kwargs) -> None:
        if args:
            if len(args) > 1:
                raise ValueError("If a position argument is used, only 1 is allowed to set `actual_instance`")
            if kwargs:
                raise ValueError("If a position argument is used, keyword arguments cannot be used.")
            super().__init__(actual_instance=args[0])
        else:
            super().__init__(**kwargs)

    @field_validator('actual_instance')
    def actual_instance_must_validate_oneof(cls, v):
        instance = Pay202Response.model_construct()
        error_messages = []
        match = 0
        # validate data type: Decision
        if not isinstance(v, Decision):
            error_messages.append(f"Error! Input type `{type(v)}` is not `Decision`")
        else:
            match += 1
        # validate data type: PendingSettlement
        if not isinstance(v, PendingSettlement):
            error_messages.append(f"Error! Input type `{type(v)}` is not `PendingSettlement`")
        else:
            match += 1
        if match > 1:
            # more than 1 match
            raise ValueError("Multiple matches found when setting `actual_instance` in Pay202Response with oneOf schemas: Decision, PendingSettlement. Details: " + ", ".join(error_messages))
        elif match == 0:
            # no match
            raise ValueError("No match found when setting `actual_instance` in Pay202Response with oneOf schemas: Decision, PendingSettlement. Details: " + ", ".join(error_messages))
        else:
            return v

    @classmethod
    def from_dict(cls, obj: Union[str, Dict[str, Any]]) -> Self:
        return cls.from_json(json.dumps(obj))

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Returns the object represented by the json string"""
        instance = cls.model_construct()
        error_messages = []
        match = 0

        # deserialize data into Decision
        try:
            instance.actual_instance = Decision.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into PendingSettlement
        try:
            instance.actual_instance = PendingSettlement.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))

        if match > 1:
            # more than 1 match
            raise ValueError("Multiple matches found when deserializing the JSON string into Pay202Response with oneOf schemas: Decision, PendingSettlement. Details: " + ", ".join(error_messages))
        elif match == 0:
            # no match
            raise ValueError("No match found when deserializing the JSON string into Pay202Response with oneOf schemas: Decision, PendingSettlement. Details: " + ", ".join(error_messages))
        else:
            return instance

    def to_json(self) -> str:
        """Returns the JSON representation of the actual instance"""
        if self.actual_instance is None:
            return "null"

        if hasattr(self.actual_instance, "to_json") and callable(self.actual_instance.to_json):
            return self.actual_instance.to_json()
        else:
            return json.dumps(self.actual_instance)

    def to_dict(self) -> Optional[Union[Dict[str, Any], Decision, PendingSettlement]]:
        """Returns the dict representation of the actual instance"""
        if self.actual_instance is None:
            return None

        if hasattr(self.actual_instance, "to_dict") and callable(self.actual_instance.to_dict):
            return self.actual_instance.to_dict()
        else:
            # primitive type
            return self.actual_instance

    def to_str(self) -> str:
        """Returns the string representation of the actual instance"""
        return pprint.pformat(self.model_dump())


