# coding: utf-8

"""
    General Liquidity: The Machine Economy API

    General Liquidity (GL) is one governed surface over payment, commerce, identity, and provenance for the machine economy. A caller submits a signed `Intent`, a deny-first gate decides, and only the server holds the settle primitive, so the caller never does. The wire convention is `snake_case`. 

    The version of the OpenAPI document: 2026-07-26
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from general_liquidity.models.evidence_class import EvidenceClass
from typing import Optional, Set
from typing_extensions import Self

class PendingSettlement(BaseModel):
    """
    An RFC 7807 problem (type `clearing.pending`) returned when an optional PENDING clearing band holds a bound spend: it was gated and authorized, but the obligation's admissibility floor is not yet met and the deadline has not passed, so the value is HELD rather than settled or refused. Retry once admissible evidence exists (the hold auto-releases to a `Receipt`); the hold refuses once the deadline passes. Only present on a stack that wired the clearing band's PENDING state. 
    """ # noqa: E501
    type: StrictStr
    title: StrictStr
    obligation_id: StrictStr = Field(description="The obligation the spend is conditional on.")
    state: StrictStr
    awaiting: EvidenceClass = Field(description="The admissibility class still awaited before the spend can settle.")
    achieved_class: Optional[EvidenceClass] = Field(default=None, description="The strongest class the admitted evidence has reached so far.")
    __properties: ClassVar[List[str]] = ["type", "title", "obligation_id", "state", "awaiting", "achieved_class"]

    @field_validator('type')
    def type_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['clearing.pending']):
            raise ValueError("must be one of enum values ('clearing.pending')")
        return value

    @field_validator('state')
    def state_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['pending']):
            raise ValueError("must be one of enum values ('pending')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of PendingSettlement from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of PendingSettlement from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "type": obj.get("type"),
            "title": obj.get("title"),
            "obligation_id": obj.get("obligation_id"),
            "state": obj.get("state"),
            "awaiting": obj.get("awaiting"),
            "achieved_class": obj.get("achieved_class")
        })
        return _obj


