# coding: utf-8

"""
    General Liquidity: The Machine Economy API

    General Liquidity (GL) is one governed surface over payment, commerce, identity, and provenance for the machine economy. A caller submits a signed `Intent`, a deny-first gate decides, and only the server holds the settle primitive, so the caller never does. Field names are `camelCase` on the wire, identical to the TypeScript spelling in `packages/surface`, so nothing is renamed between the typed client and the server that validates it. Three OUTBOUND-ONLY envelopes predate that rule and are still emitted `snake_case`: `Page`, `Job` and `WebhookEvent`. They are documented as served, and no request body carries them. 

    The version of the OpenAPI document: 2026-07-26
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from general_liquidity.models.problem_approval import ProblemApproval
from typing import Optional, Set
from typing_extensions import Self

class Problem(BaseModel):
    """
    RFC 9457 problem detail. For an agent the error IS the recovery instruction: `action` is the closed four-value class to branch on, `code` is the stable machine token behind it, and `retryAfter` is a valid-retry hint. 
    """ # noqa: E501
    type: StrictStr = Field(description="Dereferenceable per-code guidance, `https://docs.generalliquidity.com/problems/{code}`. Never `about:blank`: an agent that hits an error can fetch the explanation for exactly this code without a human in the loop. ")
    title: StrictStr = Field(description="Short, human-readable summary of the problem type.")
    status: StrictInt = Field(description="HTTP status code.")
    detail: StrictStr = Field(description="Human-readable explanation specific to this occurrence.")
    code: StrictStr = Field(description="Stable machine code an agent branches on, e.g. \"intent.denied\" | \"rate_limited\". The memory group adds: \"memory.denied\" (403, engine refused a gated write), \"memory.forbidden\" (403, mandate scope/capability refusal), and \"memory.pending\" (202, write parked for operator confirmation). ")
    action: StrictStr = Field(description="What the caller should do next. Switch on this, not on `code`: new codes arrive over time and a client branching on `code` breaks when one does, while these four classes are closed. ")
    retryable: StrictBool = Field(description="Derived from `action`. Kept so existing clients reading a boolean still work.")
    retry_after: Optional[StrictInt] = Field(default=None, description="Valid-retry hint in seconds; absent when the call must not be retried as-is.", alias="retryAfter")
    reasons: Optional[List[StrictStr]] = Field(default=None, description="Structural context, e.g. the gate's reasons behind a refusal.")
    approval: Optional[ProblemApproval] = None
    current_state_token: Optional[StrictStr] = Field(default=None, description="Set on `state.stale`: the global state token the kernel actually holds.", alias="currentStateToken")
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = ["type", "title", "status", "detail", "code", "action", "retryable", "retryAfter", "reasons", "approval", "currentStateToken"]

    @field_validator('action')
    def action_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['never-retry', 'retry-as-is', 'retry-after-renegotiation', 'escalate-to-human']):
            raise ValueError("must be one of enum values ('never-retry', 'retry-as-is', 'retry-after-renegotiation', 'escalate-to-human')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of Problem from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set([
            "additional_properties",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of approval
        if self.approval:
            _dict['approval'] = self.approval.to_dict()
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of Problem from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "type": obj.get("type"),
            "title": obj.get("title"),
            "status": obj.get("status"),
            "detail": obj.get("detail"),
            "code": obj.get("code"),
            "action": obj.get("action"),
            "retryable": obj.get("retryable"),
            "retryAfter": obj.get("retryAfter"),
            "reasons": obj.get("reasons"),
            "approval": ProblemApproval.from_dict(obj["approval"]) if obj.get("approval") is not None else None,
            "currentStateToken": obj.get("currentStateToken")
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj


