# coding: utf-8

"""
    General Liquidity: The Machine Economy API

    General Liquidity (GL) is one governed surface over payment, commerce, identity, and provenance for the machine economy. A caller submits a signed `Intent`, a deny-first gate decides, and only the server holds the settle primitive, so the caller never does. The wire convention is `snake_case`. 

    The version of the OpenAPI document: 2026-07-25
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from typing import Optional, Set
from typing_extensions import Self

class Problem(BaseModel):
    """
    RFC 7807 problem detail. For an agent the error IS the recovery instruction: `code` is a stable machine token to branch on and `retry_after` is a valid-retry hint. 
    """ # noqa: E501
    type: StrictStr = Field(description="A URI reference identifying the problem type.")
    title: StrictStr = Field(description="Short, human-readable summary of the problem type.")
    status: Annotated[int, Field(le=599, strict=True, ge=100)] = Field(description="HTTP status code.")
    detail: Optional[StrictStr] = Field(default=None, description="Human-readable explanation specific to this occurrence.")
    instance: Optional[StrictStr] = None
    code: Optional[StrictStr] = Field(default=None, description="Stable machine code an agent branches on, e.g. \"over_mandate\" | \"rate_limited\". The memory group adds: \"memory.denied\" (403, engine refused a gated write), \"memory.forbidden\" (403, mandate scope/capability refusal), and \"memory.pending\" (202, write parked for operator confirmation). ")
    retry_after: Optional[StrictInt] = Field(default=None, description="Valid-retry hint in seconds; absent when the call must not be retried as-is.")
    __properties: ClassVar[List[str]] = ["type", "title", "status", "detail", "instance", "code", "retry_after"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of Problem from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of Problem from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "type": obj.get("type") if obj.get("type") is not None else 'about:blank',
            "title": obj.get("title"),
            "status": obj.get("status"),
            "detail": obj.get("detail"),
            "instance": obj.get("instance"),
            "code": obj.get("code"),
            "retry_after": obj.get("retry_after")
        })
        return _obj


