# coding: utf-8

"""
    General Liquidity: The Machine Economy API

    General Liquidity (GL) is one governed surface over payment, commerce, identity, and provenance for the machine economy. A caller submits a signed `Intent`, a deny-first gate decides, and only the server holds the settle primitive, so the caller never does. The wire convention is `snake_case`. 

    The version of the OpenAPI document: 2026-07-26
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from general_liquidity.models.memory_mandate import MemoryMandate
from typing import Optional, Set
from typing_extensions import Self

class RecallRequest(BaseModel):
    """
    A point-in-time read. The mandate needs `canRead`.
    """ # noqa: E501
    mandate: MemoryMandate
    valid_at: datetime = Field(alias="validAt")
    tx_at: datetime = Field(alias="txAt")
    namespace: Optional[StrictStr] = None
    __properties: ClassVar[List[str]] = ["mandate", "validAt", "txAt", "namespace"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of RecallRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of mandate
        if self.mandate:
            _dict['mandate'] = self.mandate.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of RecallRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "mandate": MemoryMandate.from_dict(obj["mandate"]) if obj.get("mandate") is not None else None,
            "validAt": obj.get("validAt"),
            "txAt": obj.get("txAt"),
            "namespace": obj.get("namespace")
        })
        return _obj


