# coding: utf-8

"""
    General Liquidity: The Machine Economy API

    General Liquidity (GL) is one governed surface over payment, commerce, identity, and provenance for the machine economy. A caller submits a signed `Intent`, a deny-first gate decides, and only the server holds the settle primitive, so the caller never does. The wire convention is `snake_case`. 

    The version of the OpenAPI document: 2026-07-26
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from general_liquidity.models.memory_mandate import MemoryMandate
from general_liquidity.models.remember_request_edges_inner import RememberRequestEdgesInner
from typing import Optional, Set
from typing_extensions import Self

class RememberRequest(BaseModel):
    """
    A gated memory write. The mandate needs `canWrite`.
    """ # noqa: E501
    mandate: MemoryMandate
    body: Optional[Any] = None
    valid_from: datetime = Field(alias="validFrom")
    valid_to: Optional[datetime] = Field(alias="validTo")
    edges: Optional[List[RememberRequestEdgesInner]] = None
    source: StrictStr
    __properties: ClassVar[List[str]] = ["mandate", "body", "validFrom", "validTo", "edges", "source"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of RememberRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of mandate
        if self.mandate:
            _dict['mandate'] = self.mandate.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in edges (list)
        _items = []
        if self.edges:
            for _item_edges in self.edges:
                if _item_edges:
                    _items.append(_item_edges.to_dict())
            _dict['edges'] = _items
        # set to None if body (nullable) is None
        # and model_fields_set contains the field
        if self.body is None and "body" in self.model_fields_set:
            _dict['body'] = None

        # set to None if valid_to (nullable) is None
        # and model_fields_set contains the field
        if self.valid_to is None and "valid_to" in self.model_fields_set:
            _dict['validTo'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of RememberRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "mandate": MemoryMandate.from_dict(obj["mandate"]) if obj.get("mandate") is not None else None,
            "body": obj.get("body"),
            "validFrom": obj.get("validFrom"),
            "validTo": obj.get("validTo"),
            "edges": [RememberRequestEdgesInner.from_dict(_item) for _item in obj["edges"]] if obj.get("edges") is not None else None,
            "source": obj.get("source")
        })
        return _obj


