# coding: utf-8

"""
    General Liquidity — The Machine Economy API

    General Liquidity (GL) is the governed, unified interface for the machine economy. A caller submits a signed `Intent`; the sovereign gate decides and only the server holds the settle primitive — the caller never reaches it (DESIGN §7, sovereign settle-separation).  This document is the **single source of truth** for the GL surface. The typed SDK (`packages/sdk`) and the MCP server (`packages/mcp`) are generated projections of this spec via Speakeasy (BUILD-PLAN §5).  Naming is canonical per `docs/NAMING.md`: verbs are single common English words (`resolve`, `pay`, `verify`, `disclose`, `buy`, `quote`); nouns are concrete singular domain objects (`Intent`, `Mandate`, `Receipt`, `Counterparty`). The wire is `snake_case`; the TypeScript SDK presents `camelCase`. Vendor/protocol names appear only as lowercase `RailId` values, never as verbs or types. 

    The version of the OpenAPI document: 2026-07-22
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List
from typing import Optional, Set
from typing_extensions import Self

class ResolveRequest(BaseModel):
    """
    ResolveRequest
    """ # noqa: E501
    ref: StrictStr = Field(description="A2A card URL, signed disclosure id, or CAIP-10 account.")
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = ["ref"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ResolveRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set([
            "additional_properties",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ResolveRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "ref": obj.get("ref")
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj


