# coding: utf-8

"""
    General Liquidity: The Machine Economy API

    General Liquidity (GL) is one governed surface over payment, commerce, identity, and provenance for the machine economy. A caller submits a signed `Intent`, a deny-first gate decides, and only the server holds the settle primitive, so the caller never does. The wire convention is `snake_case`. 

    The version of the OpenAPI document: 2026-07-25
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class Reversibility(str, Enum):
    """
    Reversibility
    """

    """
    allowed enum values
    """
    REVERSIBLE = 'reversible'
    IRREVERSIBLE = 'irreversible'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of Reversibility from a JSON string"""
        return cls(json.loads(json_str))


