# coding: utf-8

"""
    General Liquidity: The Machine Economy API

    General Liquidity (GL) is one governed surface over payment, commerce, identity, and provenance for the machine economy. A caller submits a signed `Intent`, a deny-first gate decides, and only the server holds the settle primitive, so the caller never does. Field names are `camelCase` on the wire, identical to the spelling the typed clients use, so nothing is renamed between a client and the server that validates it. Three OUTBOUND-ONLY envelopes predate that rule and are still emitted `snake_case`: `Page`, `Job` and `WebhookEvent`. They are documented as served, and no request body carries them. 

    The version of the OpenAPI document: 2026-07-28
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List
from general_liquidity.models.capital_source import CapitalSource
from general_liquidity.models.finality import Finality
from general_liquidity.models.presence import Presence
from general_liquidity.models.rail_id import RailId
from general_liquidity.models.reversibility import Reversibility
from typing import Optional, Set
from typing_extensions import Self

class Terms(BaseModel):
    """
    The six irreducible fields — explicit on every Intent and Receipt, never silently defaulted. This is what the Gate reasons over. 
    """ # noqa: E501
    reversibility: Reversibility
    finality: Finality
    credential: StrictStr = Field(description="Authorization model id, e.g. \"eip3009\" | \"vc-mandate\" | \"http-sig\".")
    rail: RailId
    capital_source: CapitalSource = Field(alias="capitalSource")
    presence: Presence
    __properties: ClassVar[List[str]] = ["reversibility", "finality", "credential", "rail", "capitalSource", "presence"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of Terms from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of Terms from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "reversibility": obj.get("reversibility"),
            "finality": obj.get("finality"),
            "credential": obj.get("credential"),
            "rail": obj.get("rail"),
            "capitalSource": obj.get("capitalSource"),
            "presence": obj.get("presence")
        })
        return _obj


